name: CI Pipeline - Test, Build, Trigger GitOps

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: yashwanth0422/sample-flask
  GITOPS_REPO: https://github.com/Yashwanth0422/gitops-repo.git

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

  build:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker push $IMAGE_NAME:${{ github.sha }}

  trigger-gitops:
    name: Update GitOps Repo to Trigger Deployment
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Clone gitops repo
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git clone https://x-access-token:${GH_TOKEN}@github.com/Yashwanth0422/gitops-repo.git
        cd gitops-repo
        sed -i "s|image: .*/sample-flask:.*|image: $IMAGE_NAME:${GITHUB_SHA}|g" deployment.yaml
        git config user.email "ci-bot@yashwanth0422.com"
        git config user.name "CI Bot"
        git add deployment.yaml
        git commit -m "Update image tag to $IMAGE_NAME:${GITHUB_SHA} [ci skip]"
        git push origin main
