name: Build, Test & Push

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout add-repo
      - name: Checkout add-repo
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker registry
      - name: Docker login
        uses: docker/login-action@v2
