name: Build & Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout add-repo
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s app/tests

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout add-repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/sample-webapp:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE -f app/Dockerfile .
          docker push $IMAGE

  trigger:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger GitOps Deployment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Yashwanth0422/gitops-repo/dispatches \
            -d '{"event_type":"update-deployment","client_payload":{"image_tag":"'"${GITHUB_SHA}"'"}}'
