name: Build & Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Stage
    runs-on: ubuntu-latest

    steps:
      # Checkout add-repo source code
      - name: Checkout add-repo
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker registry
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build & Push Docker image
        run: |
          IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/sample-webapp:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE -f app/Dockerfile .
          docker push $IMAGE

      # Run unit tests
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s app/tests
          
name: Trigger GitOps Deployment

# Trigger manually or via API, or from another workflow
on:
  workflow_run:
    workflows: ["Build & Test"]
    types:
      - completed

jobs:
  trigger-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitOps Deployment workflow
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}               # Personal Access Token with write access
          repository: Yashwanth0422/gitops-repo       # GitOps repo
          workflow: GitOps Deployment.yml             # Exact workflow filename in gitops-repo
          ref: main                                   # Branch to run
          inputs: |
            image_tag: ${{ github.event.workflow_run.head_sha }}  # Pass image tag from build
       
