name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/your-username/sample-webapp:${{ github.sha }} .
          docker push docker.io/your-username/sample-webapp:${{ github.sha }}

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

      - name: Update gitops repo with new image tag
        env:
          GITOPS_REPO: https://github.com/Yashwanth0422/add-repo.git
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git clone $GITOPS_REPO
          cd gitops-repo
          sed -i "s|image: docker.io/your-username/sample-webapp:.*|image: docker.io/your-username/sample-webapp:${IMAGE_TAG}|g" deployment.yaml
          git config user.email "ci@example.com"
          git config user.name "CI Bot"
          git add deployment.yaml
          git commit -m "Deploy image tag ${IMAGE_TAG}"
          git push origin main
