name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/ubuntu1:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE -f app/Dockerfile .
          docker push $IMAGE

  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

      - name: Set up kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: ci-smoke-test

      - name: Deploy to kind
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/deployment1 --timeout=60s
          kubectl get pods -o wide

      - name: Run smoke tests
        run: |
          curl -f http://localhost:8080/ || exit 1

  gitops:
    name: GitOps Deployment Stage
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v3
        with:
          repository: Yashwanth0422/gitops-repo   # fixed (no https://)
          token: ${{ secrets.PAT_TOKEN }}
          path: gitops-repo

      - name: Update deployment manifest
        run: |
          cd gitops-repo
          sed -i "s|image: .*|image: docker.io/${{ secrets.DOCKER_USERNAME }}/ubuntu1:${{ github.sha }}|g" deployment.yaml
          git config user.email "ci@example.com"
          git config user.name "CI Bot"
          git add deployment.yaml
          git commit -m "Deploy image tag ${{ github.sha }}"
          git push origin main
